### PR TITLE
new automatic differentiation howto

### PR DESCRIPTION
**Pull request by owulveryck**

### CODE REVIEW

**Comment by owulveryck** [comment]
@mattn I changed a bit this howto, but I am waiting a review from @chewxy to be sure that I did not wrote anything wrong.

**Comment by owulveryck** [comment]
@chewxy if you have a bit of time, I'd like a quick review of this to make sure I did not write anything wrong. Thanks.

**Comment by chewxy** [comment]
Will do in 2 hrs

**Comment by chewxy** [comment]
No obvious flaws. Some grammatical errors and some omissions. I've fixed those that I can see. Some links are broken but I'll add those.

**Comment by chewxy** [comment]
TLDR: LGTM

**Comment by chewxy** [comment]
Any idea why the `-12` isn't showing up?

image

The mermaidjs is as follows:

```mermaid
mul(*) -->|$f=-12$<br>$1$| f
```

which clearly has the `-12`

**Comment by chewxy** [comment]
In fact, the `-12` flashes for a bit then disappears.

**Review by chewxy — APPROVED** [review]

**Pull request merged**
